version: '3.4'

services:
  clientapp:
    image: clientapp
    build:
      context: client-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
